services:
  - type: web
    name: trec-classifier
    runtime: docker
    buildCommand: make build_app
    startCommand: make run_app
    plan: free
    ports:
      - 5000
    dockerfilePath: ./inference.Dockerfile
    branch: main
