step_to_execute: "train"

mlflow:
  mlflow_uri: "http://mlflow-server:5001"

training:
  batch_size: 16
  max_length: 128
  n_classes: 6
  learning_rate: 0.00001
  max_epochs: 6
  dataset_name: "trec"
  seed: 42
  test_size: 0.2
  n_workers: 8
  pretrained_model_name: "prajjwal1/bert-tiny"
  output_model_pytorch: "model.pth"
  output_model_onnx: "model.onnx"

inference:
  model_type: "onnx"
  onnx_model_uri: "mlflow-artifacts:/588397206089841990/55f66a78826c4b9a86d093c514dba3be/artifacts/model"

flask:
  host: "0.0.0.0"
  port: 5001