step_to_execute: "train"

mlflow:
  mlflow_uri: "http://mlflow-server:5001"

data:
  s3_bucket: "document-classification-2024"
  s3_prefix: "data"
  local_uri: "data-downloaded"

model:
  batch_size: 16
  max_length: 128
  n_classes: 6
  learning_rate: 0.00001
  max_epochs: 6
  pretrained_model_name: "prajjwal1/bert-tiny"
  output_model_pytorch: "model.pth"
  output_model_onnx: "model.onnx"

experiment:
  test_size: 0.2
  n_workers: 8
  seed: 42

inference:
  onnx_model_uri: "models:/trec-classifier/1"
  artifacts_uri: "artifacts"

flask:
  host: "0.0.0.0"
  port: 5001